apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.51.61
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-pv
spec:
  containers:
    - image: centos:7
      name: test-container
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: aws-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-pv1
spec:
  containers:
    - image: centos:7
      name: test-container
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: aws-pvc